### ISSUE TITLE
New-IntuneWin fails if -DownloadContent is not specified.

### ISSUE THREAD

**Issue by cclifton7** [byteben/Win32App-Migration-Tool#12] opened 2023-11-14 13:47 UTC
The New-IntuneWin function is using the 'C:\Win32AppMigrationTool\Content' as the source instead of the actual source when DownloadContent is not specified.  This of course causes IntuneWinAppUtil.exe to fail since the source files are not present in the 'C:\Win32AppMigrationTool\Content' folder.

Is anyone else having this issue?

**Comment by byteben** [comment] 2023-11-25 14:03
Can you share the log please?

**Comment by obuolinis** [comment] 2023-12-01 16:26
Oh yeah I noticed this as well.
I think the problem is with this line: https://github.com/byteben/Win32App-Migration-Tool/blob/138fad5cb5206394dee2ff90f93f112bf44af1ae/Public/New-Win32App.ps1#L352
Here you're passing a content destination folder to New-IntuneWin in all cases, even though it exists only if I use DownloadContent parameter.

Something like this should do the trick:
`if ($DownloadContent) {
    $paramsToPassIntuneWin.Add('ContentFolder', $content.Install_Destination)
}
else {
    $paramsToPassIntuneWin.Add('ContentFolder', $content.Install_Source)
}
`

**Comment by byteben** [comment] 2023-12-16 12:04
Thank you @cclifton7 and @obuolinis this issue has been resolved in branch https://github.com/byteben/Win32App-Migration-Tool/tree/version-2.0.19 for New-Win32app.ps1
One thing I will need to consider when letting folks use the ConfigMgr source to build .intunewin files is how to deal with uninstall content if is in a different location. Currently we account for this and can handle it when staging the content locally

**Closed by byteben** 2023-12-16 12:04 UTC
